<a href="https://colab.research.google.com/github/iepetrov/jose_TF_DL_inPy/blob/master/ex_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
# Basic constant operations
# The value returned by the constructor represents the output
# of the Constant op.
a = tf.constant(2)
b = tf.constant(3)

In [4]:
# Launch the default graph.
with tf.Session() as sess:
    print("a=2, b=3")
    print("Addition with constants: %i" % sess.run(a+b))
    print("Multiplication with constants: %i" % sess.run(a*b))

a=2, b=3
Addition with constants: 5
Multiplication with constants: 6


In [0]:
# Basic Operations with variable as graph input
# The value returned by the constructor represents the output
# of the Variable op. (define as input when running session)
# tf Graph input
a = tf.placeholder(tf.int16)
b = tf.placeholder(tf.int16)

In [0]:
# Define some operations
add = tf.add(a, b)
mul = tf.multiply(a, b)

In [7]:
# Launch the default graph.
with tf.Session() as sess:
    # Run every operation with variable input
    print("Addition with variables: %i" % sess.run(add, feed_dict={a: 2, b: 3}))
    print("Multiplication with variables: %i" % sess.run(mul, feed_dict={a: 2, b: 3}))

Addition with variables: 5
Multiplication with variables: 6


In [0]:
# ----------------
# More in details:
# Matrix Multiplication from TensorFlow official tutorial

# Create a Constant op that produces a 1x2 matrix.  The op is
# added as a node to the default graph.
#
# The value returned by the constructor represents the output
# of the Constant op.
matrix1 = tf.constant([[3., 3.]])

In [0]:
# Create another Constant that produces a 2x1 matrix.
matrix2 = tf.constant([[2.],[2.]])

In [0]:
# Create a Matmul op that takes 'matrix1' and 'matrix2' as inputs.
# The returned value, 'product', represents the result of the matrix
# multiplication.
product = tf.matmul(matrix1, matrix2)

In [14]:
# To run the matmul op we call the session 'run()' method, passing 'product'
# which represents the output of the matmul op.  This indicates to the call
# that we want to get the output of the matmul op back.
#
# All inputs needed by the op are run automatically by the session.  They
# typically are run in parallel.
#
# The call 'run(product)' thus causes the execution of threes ops in the
# graph: the two constants and matmul.
#
# The output of the op is returned in 'result' as a numpy `ndarray` object.
with tf.Session() as sess:
    result = sess.run(product)
    print(result)
    # ==> [[ 12.]]

[[12.]]


In [15]:
# Add
tensor_a = tf.constant([[1,2]], dtype = tf.int32)
tensor_b = tf.constant([[3, 4]], dtype = tf.int32)

tensor_add = tf.add(tensor_a, tensor_b)
print(tensor_add)

Tensor("Add_2:0", shape=(1, 2), dtype=int32)


In [17]:
with tf.Session() as sess:
    result = sess.run(tensor_add)
    print(result)

[[4 6]]


In [18]:
tensor_mult = tf.multiply(tensor_a, tensor_b)
with tf.Session() as sess:
    result1 = sess.run(tensor_mult)
    print(result1)

[[3 8]]


In [19]:
tensor_a = tf.constant([[1],[2]], dtype = tf.int32)
tensor_b = tf.constant([[3, 4]], dtype = tf.int32)
tensor_mult = tf.multiply(tensor_a, tensor_b)
with tf.Session() as sess:
    result1 = sess.run(tensor_mult)
    print(result1)

[[3 4]
 [6 8]]


In [21]:
tensor_a = tf.constant([[1,2]], dtype = tf.int32)
tensor_b = tf.constant([[3],[4]], dtype = tf.int32)
tensor_mult = tf.multiply(tensor_a, tensor_b)
with tf.Session() as sess:
    result1 = sess.run(tensor_mult)
    print(result1)

[[3 6]
 [4 8]]


In [22]:
tensor_a = tf.constant([[1],[2]], dtype = tf.int32)
tensor_b = tf.constant([[3, 4]], dtype = tf.int32)
tensor_mult = tf.matmul(tensor_a, tensor_b)
with tf.Session() as sess:
    result1 = sess.run(tensor_mult)
    print(result1)

[[3 4]
 [6 8]]


In [23]:
tensor_a = tf.constant([[1,2]], dtype = tf.int32)
tensor_b = tf.constant([[3],[4]], dtype = tf.int32)
tensor_mult = tf.matmul(tensor_a, tensor_b)
with tf.Session() as sess:
    result1 = sess.run(tensor_mult)
    print(result1)

[[11]]


In [27]:
import numpy as np

data_placeholder_a = tf.placeholder(tf.float32, name = "data_placeholder_a")
print(data_placeholder_a)

power_a = tf.pow(data_placeholder_a, 2) 

with tf.Session() as sess:  
  data = np.random.rand(1, 10)  
  print(sess.run(power_a, feed_dict={data_placeholder_a: data}))

Tensor("data_placeholder_a:0", dtype=float32)
[[0.12524186 0.54878324 0.37933198 0.08577479 0.63997847 0.6915299
  0.9082213  0.5659813  0.3355632  0.00099745]]
